version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://mongo:27017/web-engineering
      - APP_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
